# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd48c8c62a10553b2fb5a763bb4c8d18c3db0244286b4dd4083e12a66c38167179d8cdf71b07b600b167c1de7b19de77e58de233c80386fb4d845ff1bf1b20e

test:
  secret_key_base: 1463642387d48cc4fcf120808710db03cb942e4842ff431fea964b7350a20d2bd658ce7f7241f5613b8eae24686d1e08fb922c04a460f141c22dd202722689c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
